const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Mouse,
		C3.Plugins.Keyboard,
		C3.Plugins.Sprite,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Behaviors.Fade,
		C3.Behaviors.scrollto,
		C3.Behaviors.bound,
		C3.Behaviors.EightDir,
		C3.Plugins.Text,
		C3.Plugins.Button,
		C3.Plugins.AJAX,
		C3.Plugins.TextBox,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.TextBox.Acts.SetVisible,
		C3.Plugins.Button.Acts.SetVisible,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.AJAX.Acts.Request,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.RotateTowardPosition,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.System.Exps.replace,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.AJAX.Acts.Post,
		C3.Plugins.TextBox.Exps.Text
	];
};
self.C3_JsPropNameTable = [
	{PlanoDeFundoEmBlocos: 0},
	{PlanoDeFundoEmBlocos2: 0},
	{PlanoDeFundoEmBlocos3: 0},
	{Mouse: 0},
	{Teclado: 0},
	{Vida: 0},
	{Projétil: 0},
	{Villain: 0},
	{DestruirForaDoLayout: 0},
	{Bullet: 0},
	{Esmaecer: 0},
	{Explosion: 0},
	{Canhão: 0},
	{CentrarEm: 0},
	{RestritoAoLayout: 0},
	{"8Direções": 0},
	{Shooter: 0},
	{Pontuação: 0},
	{Canhao: 0},
	{Botão: 0},
	{AJAX: 0},
	{GameOverText: 0},
	{NomeJogador: 0},
	{Enviar: 0},
	{RankingJogadores: 0},
	{Aviso: 0},
	{Pontos: 0}
];

self.InstanceType = {
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos2: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos3: class extends self.ITiledBackgroundInstance {},
	Mouse: class extends self.IInstance {},
	Teclado: class extends self.IInstance {},
	Villain: class extends self.ISpriteInstance {},
	Bullet: class extends self.ISpriteInstance {},
	Explosion: class extends self.ISpriteInstance {},
	Shooter: class extends self.ISpriteInstance {},
	Pontuação: class extends self.ITextInstance {},
	Vida: class extends self.ITextInstance {},
	Canhao: class extends self.ISpriteInstance {},
	Botão: class extends self.IButtonInstance {},
	AJAX: class extends self.IInstance {},
	GameOverText: class extends self.ITextInstance {},
	NomeJogador: class extends self.ITextInputInstance {},
	Enviar: class extends self.IButtonInstance {},
	RankingJogadores: class extends self.ITextInstance {},
	Aviso: class extends self.ITextInstance {}
}